# Generated by Django 5.2.11 on 2026-02-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_tags_comment_image_comment_is_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
