# Generated by Django 5.2.11 on 2026-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
