# Generated by Django 5.2.11 on 2026-02-16 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_superadmin_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions_level', models.IntegerField(default=1, help_text='Higher number = more permissions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SuperAdmin Type',
                'verbose_name_plural': 'SuperAdmin Types',
                'db_table': 'superadmin_types',
                'ordering': ['permissions_level'],
            },
        ),
        migrations.AddField(
            model_name='superadmin',
            name='admin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmins', to='blog.superadmintype'),
        ),
    ]
